name: 01.07.00.$(BuildID)$(Rev:.r)

trigger: none
resources:
  repositories:
  - repository: kube
    type: git
    name: logmonitorin
    #ref: pp_796513_vmrg_devop
    ref: main

variables:
  buildConfiguration: 'Release'
  system.debug: true

pool: 
  vmImage: 'ubuntu-18.04'

steps:
- checkout: kube
  #path: s/kube
  submodules: recursive
  clean: true
  persistCredentials: true


- task: ShellScript@2
  inputs:
    scriptPath: $(System.DefaultWorkingDirectory)/build.sh
