name: 01.07.00.$(BuildID)$(Rev:.r)

trigger: none
resources:
  repositories:
  - repository: kube
    type: git
    name: logmonitorin
    #ref: pp_796513_vmrg_devop
    ref: main

pool: 
  vmImage: 'ubuntu-18.04'

steps:
- checkout: kube
  #path: s/kube
  submodules: recursive
  clean: true
  persistCredentials: true

stages:
  - stage: build
    displayName: Build & Test
    jobs:
    - job: build_test
      displayName: Build Loggin-Monitoring jar
    - script: |
         #cd build/scripts
         printf "${BUILD_BUILDNUMBER}\nY\n" | bash  build.sh
      displayName: Package
    - task: PublishPipelineArtifact@1
      inputs:
      path: $(System.DefaultWorkingDirectory)/build/dist
      artifact: dist
    - stage: build
      displayName: Build & Test
      jobs:
        - job: build_test
          displayName: Build QC Warehouse
    