name: 2.7.0.$(BuildID)$(Rev:.r)
trigger: none
resources:
  repositories:
  - repository: kube
    type: GitHub
    name: piyushpurohit23/logmonitorin
    #ref: pp_796513_vmrg_devops
    ref: main
    endpoint: github.com_piyushpurohit23

pool:
  vmImage: 'ubuntu-18.04'
#container: atria-java

steps:
- checkout: kube
  #path: s/kube
  submodules: recursive
  clean: true
  persistCredentials: true
#- task: MavenAuthenticate@0
#  displayName: 'Maven Authenticate'
#  inputs:
#    artifactsFeeds: atria_vmrg_artifact_repo
- task: Maven@3
  inputs:
    mavenPomFile: '$(System.DefaultWorkingDirectory)/src/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    #jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    mavenAuthenticateFeed: false
    effectivePomSkip: false 
    sonarQubeRunAnalysis: false
    #goals: 'deploy -Dbuildversion=$(Build.BuildNumber) -X'
    goals: 'deploy'
- script: |
    mkdir -p distribution/deploy
- task: PublishPipelineArtifact@1
  inputs: 
    path: '$(System.DefaultWorkingDirectory)/src/target/'
    artifact: dist
